[env:Esp32Dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = custom_4Mb_full.csv
build_src_filter = ${env.build_src_filter} +<../boards/Esp32Dev>

build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/Esp32Dev

	; -------------------------------------------------------------------------
	; Global SPI Bus Pins (VSPI)
	; -------------------------------------------------------------------------
	-DSPI_SCK_PIN=18
	-DSPI_MOSI_PIN=23
	-DSPI_MISO_PIN=19
	-DSPI_SS_PIN=5

	; -------------------------------------------------------------------------
	; Screen Setup (ST7789 1.47" SPI 4-Wire)
	; -------------------------------------------------------------------------
	;-DHAS_SCREEN=1
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=172
	-DTFT_HEIGHT=320
	-DROTATION=3
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1        ; ไม่ใช้ GPIO (ต่อ RST จอเข้าไฟ 3.3V หรือ EN บอร์ด)
	-DBACKLIGHT=32      ; TFT Backlight Control Pin
	-DTFT_BACKLIGHT_ON=HIGH
	-DMINBRIGHT=160
	-DSMOOTH_FONT=1

	; -------------------------------------------------------------------------
	; SD Card Setup
	; -------------------------------------------------------------------------
	-DSDCARD_CS=5
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

	; -------------------------------------------------------------------------
	; CC1101 Transceiver (ไม่ใช้ GDO2)
	; -------------------------------------------------------------------------
	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=22
	-DCC1101_SS_PIN=27
	-DCC1101_MOSI_PIN=23
	-DCC1101_SCK_PIN=18
	-DCC1101_MISO_PIN=19

	; -------------------------------------------------------------------------
	; nRF24L01 Transceiver (CS=4, CE=16)
	; -------------------------------------------------------------------------
	-DUSE_NRF24_VIA_SPI
	-DNRF24_SS_PIN=17    ; Chip Select = 4
	-DNRF24_CE_PIN=16   ; Chip Enable = 16
	-DNRF24_MOSI_PIN=23
	-DNRF24_SCK_PIN=18
	-DNRF24_MISO_PIN=19

	; -------------------------------------------------------------------------
	; Infrared (IR) Setup
	; -------------------------------------------------------------------------
	-DIR_TX_PINS='{{"Pin 22", 27}}'
	-DIR_RX_PINS='{{"Pin 27", 22}}'
	-DTXLED=-1
	-DLED_ON=HIGH
	-DLED_OFF=LOW


	; System Options
	; -------------------------------------------------------------------------
	-DFP=1
	-DFM=2
	-DFG=3
	-DSERIAL_TX=1
	-DSERIAL_RX=3
	-DGROVE_SDA=-1
	-DGROVE_SCL=-1

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}
